doctfiles update

diff --git a/git/.git-bin/add-common-remotes b/git/.git-bin/add-common-remotes
--- a/git/.git-bin/add-common-remotes
+++ b/git/.git-bin/add-common-remotes
@@ -1,5 +1,6 @@
 #!/bin/bash -e
 
+#set -x
 usage(){
     cat <<EOF
 
@@ -7,6 +8,7 @@ usage : add-common-remotes
 
       --help     -h   this help
       --dryrun   -d   dry run
+      --remove   -r   remove remotes
 
 Add common remotes which are defined in ~/.projects/projects.yaml
 EOF
@@ -20,6 +22,7 @@ fi
 readarray -t projects < <(yq e -o j -I 0 '.[]' "$HOME/.projects/projects.yaml")
 
 DRYRUN=false
+REMOVE=false
 GIT_HOSTNAME=
 GIT_PATH=
 
@@ -43,10 +46,47 @@ while (( $# != 0 )); do
     case "$1" in
         --help | -h ) usage; exit;;
         --dryrun | -d ) DRYRUN=true; shift;;
+        --remove | -r ) REMOVE=true; shift;;
         * ) break ;;
     esac
 done
 
+BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+CLONE_URL="$(git config --get remote.origin.url)"
+if [[ $DRYRUN == false ]]; then
+    git remote remove origin || true
+    git remote remove from || true
+
+    if [[ -n $CLONE_URL ]]; then
+        git remote add origin "$CLONE_URL"
+        git remote set-url --add --push origin "$CLONE_URL"
+        git remote add from "$CLONE_URL"
+        git remote set-url --add --push from "$CLONE_URL"
+        git fetch from
+    fi
+
+    if [[ -n $BRANCH ]]; then
+        git fetch
+        git branch --set-upstream-to="origin/$BRANCH"
+    fi
+else
+    cat <<EOF
+# cleanup origin
+git remote remove origin
+EOF
+    if [[ -n $CLONE_URL ]]; then
+        cat <<EOF
+git remote add origin "$CLONE_URL"
+EOF
+    fi
+fi
+
+if [[ $REMOVE == true ]]; then
+    for o in $(git remote | grep -v '^origin$'); do
+        git remote remove "$o"
+    done
+    exit
+fi
 
 for p in "${projects[@]}"; do
     project="$(yq e '.| keys | .[0]' <<< "$p")"
@@ -57,15 +97,15 @@ for p in "${projects[@]}"; do
 
     if [[ $DRYRUN == false ]]; then
         echo "adding remote: ${project} git@${git_hostname}:${project}/${path}"
-        git remote set-url --delete --push origin "git@${git_hostname}:${project}/${path}" &>/dev/null || true
         git remote set-url --add --push origin "git@${git_hostname}:${project}/${path}"
+        git remote remove "$project" &>/dev/null || true
         git remote add "$project" "git@${git_hostname}:${project}/${path}" &>/dev/null || true
     else
         cat <<EOF
 # remote for $project
-git remote set-url --delete --push origin "git@${git_hostname}:${project}/${path}"
 git remote set-url --add --push origin "git@${git_hostname}:${project}/${path}"
-git remote add "$project" "git@${git_hostname}:${project}/${path}"
+git remote remove "$project" &>/dev/null || true
+git remote add "$project" "git@${git_hostname}:${project}/${path}" &>/dev/null || true
 
 EOF
     fi
